version: '3.9'

services:
  auth-service:
    <<: *base-service
    build:
      context: ./auth
      dockerfile: Dockerfile
    environment:
      - AUTH_DB_HOST=db-service
    depends_on:
      - db-service

  db-service:
    <<: *db-service
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=coredb
      - POSTGRES_USER=coreuser
      - POSTGRES_PASSWORD=corepassword

  registry-service:
    <<: *base-service
    build:
      context: ./registry
      dockerfile: Dockerfile
    environment:
      - REGISTRY_DB_HOST=db-service
    depends_on:
      - db-service

  logs-service:
    <<: *base-service
    build:
      context: ./logs
      dockerfile: Dockerfile
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
    depends_on:
      - auth-service
      - registry-service

networks:
  core_network:
    name: core_network

volumes:
  db-data: